#!/bin/bash

cd $(dirname $0)
cd ..

# Try to use buildah
if [ -x "$(command -v buildah)" ]; then
    buildah bud -f Dockerfiles/backend.Dockerfile -t jua/backend .
    buildah bud -f Dockerfiles/frontend.Dockerfile -t jua/frontend .
else
    docker build -f Dockerfiles/backend.Dockerfile -t jua/backend .
    docker build -f Dockerfiles/frontend.Dockerfile -t jua/frontend .
fi